window.APP_CONFIG={
  bounds:[[48.865,1.608],[49.241,2.596]],
  center:[49.075,2.10],
  rpgMinZoom:12,
  communesApi:"https://geo.api.gouv.fr/departements/95/communes?format=geojson&geometry=contour",
  reverseApi:"https://geo.api.gouv.fr/communes",
  rpgApi:"https://apicarto.ign.fr/api/rpg/v2",
  osm:"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
  ortho:"https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&FORMAT=image/jpeg&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}"
};